project:
  type: website
  output-dir: ../docs

website:
  title: "nhyris user guide"
  description: "Documentation for the nhyris platform"
  repo-url: https://github.com/jahnen/nhyris
  issue-url: https://github.com/jahnen/nhyris/issues
  search: false
  favicon: brand/logo.png
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
      - href: roadmap.qmd
        text: Project Roadmap
      - href: architecture.qmd
        text: Architecture
      - href: customization.qmd
        text: Customization
      - href: troubleshooting.qmd
        text: Troubleshooting
    right:
      - icon: github
        href: https://github.com/jahnen/nhyris
  body-footer: Made by [jahnen](https://jahnen.io)
  image: brand/logo.png

format:
  html:
    theme:
      - brand
    css: styles.css
    toc: true

brand: brand/_brand.yml
