---
title: "nhyris Roadmap"
---

::: {.callout-note}
If you have ideas, it's always welcome to [submit](https://github.com/jahnen/nhyris/issues/new)
:::

### Provided Features

#### Multiple OS

- [x] macOS
- [x] Windows
- [x] Linux (Ubuntu)

#### Multiple Types of Installer

- [x] ZIP 
- [x] DMG for macOS
- [x] deb for Ubuntu
- [x] Squirrel.Windows for Windows

#### Advanced Shiny

- [x] CRAN package support
- [x] Bioconductor package support
- [x] r-universe (GitHub) package support

#### Example Shiny Application

- [x] See [shiny gallery](https://shiny.posit.co/r/gallery/)

### Planned Features

#### Advanced Electron

- [ ] Configuration of Electron (requires research)
- [ ] Code signing for macOS or Windows

### IDEAS

::: {.callout-note}
These are just ideas, which can be changed as the project evolves.
:::

#### Advanced shiny

`nhyris` only supports simple shiny application

So, allowing shiny frameworks like `rhino`, `golem`, `leprechaun`, ... maybe considered.

#### Delivering method

`nhyris` only uses `electron.js`.

But `tauri` (with rust) or utilizing user's already installed R. `npm` (as javascript package) , ... maybe considered.

